DROP DATABASE IF EXISTS YUMMYEAT;
CREATE DATABASE YUMMYEAT;
USE YUMMYEAT;

CREATE TABLE CLIENTE (
	ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
	CODIGO_COOKIE CHAR(32),
	NOMBRE_CLIENTE VARCHAR(30) NOT NULL,
	APELLIDOS_CLIENTE VARCHAR(40) NOT NULL,
	TELEFONO_CLIENTE CHAR(11) NOT NULL,
	DIRECCION_CLIENTE VARCHAR(60),
	EMAIL_CLIENTE VARCHAR(40) NOT NULL,
	UNIQUE (EMAIL_CLIENTE),
 PRIMARY KEY (ID_CLIENTE)) ENGINE = INNODB;

CREATE TABLE RESTAURANTE (
	ID_RESTAURANTE CHAR(4) NOT NULL,
	NOMBRE_RESTAURANTE VARCHAR(40) NOT NULL,
	TELEFONO_RESTAURANTE CHAR(11) NOT NULL,
	DIRECCION_RESTAURANTE VARCHAR(60) NOT NULL,
	LOCALIDAD_RESTAURANTE VARCHAR(30) NOT NULL,
	EMAIL_RESTAURANTE VARCHAR(40) NOT NULL,
	ESPECIALIDAD_RESTAURANTE VARCHAR(40) NOT NULL,
	DESTACADO_RESTAURANTE INT NOT NULL COMMENT '0 -> NO D 1 -> DESTA',
 PRIMARY KEY (ID_RESTAURANTE)) ENGINE = INNODB;

CREATE TABLE REPARTIDOR (
	ID_REPARTIDOR INT NOT NULL AUTO_INCREMENT,
	DNI_REPARTIDOR CHAR(11) NOT NULL,
	NOMBRE_REPARTIDOR VARCHAR(30) NOT NULL,
	APELLIDOS_REPARTIDOR VARCHAR(40) NOT NULL,
	TELEFONO_REPARTIDOR CHAR(11) NOT NULL,
	DIRECCION_REPARTIDOR VARCHAR(60) NOT NULL,
	EMAIL_REPARTIDOR VARCHAR(40) NOT NULL,
	SALARIO_REPARTIDOR DECIMAL(10,2) NOT NULL,
	DISPONIBILIDAD INT NOT NULL COMMENT '0 -> NO DISPONIBLE 1 -> DISPONIBLE',
	ZONA_REPARTIDOR VARCHAR(30) NOT NULL,
 PRIMARY KEY (ID_REPARTIDOR)) ENGINE = INNODB;

CREATE TABLE PRODUCTO (
	ID_PRODUCTO INT NOT NULL AUTO_INCREMENT,
	ID_RESTAURANTE CHAR(4) NOT NULL,
	NOMBRE_PRODUCTO VARCHAR(40) NOT NULL,
	DESCRIPCION_PRODUCTO VARCHAR(150) NOT NULL,
	PRECIO_PRODUCTO DECIMAL(10,2) NOT NULL,
 PRIMARY KEY (ID_PRODUCTO)) ENGINE = INNODB;

CREATE TABLE PEDIDO (
	NUMERO_PEDIDO INT NOT NULL AUTO_INCREMENT,
	ID_RESTAURANTE CHAR(4) NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_REPARTIDOR INT NOT NULL,
	DIRECCION_ENTREGA VARCHAR(60) COMMENT 'NULL -> PEDIDO NO CONFIRMADO',
	PRECIO_PEDIDO DECIMAL(10,2) NOT NULL,
	FECHA_PEDIDO_REALIZADO DATETIME COMMENT 'NULL -> PEDIDO NO CONFIRMADO',
	FECHA_PEDIDO_ENTREGADO DATETIME,
 PRIMARY KEY (NUMERO_PEDIDO)) ENGINE = INNODB;

CREATE TABLE DETALLE_PEDIDO_PRODUCTO (
	NUMERO_PEDIDO INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	PRECIO_UNITARIO_PRODUCTO DECIMAL(10,2) NOT NULL,
	UNIDADES_PRODUCTO INT NOT NULL,
 PRIMARY KEY (NUMERO_PEDIDO,ID_PRODUCTO)) ENGINE = INNODB;

CREATE TABLE MENU (
	ID_MENU INT NOT NULL AUTO_INCREMENT,
	ID_RESTAURANTE CHAR(4) NOT NULL,
	NOMBRE_MENU VARCHAR(70) NOT NULL,
	DESCRIPCION_MENU VARCHAR(150) NOT NULL,
	PRECIO_MENU DECIMAL(10,2) NOT NULL,
 PRIMARY KEY (ID_MENU)) ENGINE = INNODB;

CREATE TABLE PRODUCTOS_MENU (
	ID_MENU INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
 PRIMARY KEY (ID_MENU,ID_PRODUCTO)) ENGINE = INNODB;

CREATE TABLE DETALLE_PEDIDO_MENU (
	NUMERO_PEDIDO INT NOT NULL,
	ID_MENU INT NOT NULL,
	PRECIO_UNITARIO_MENU DECIMAL(10,2) NOT NULL,
	UNIDADES_MENU INT NOT NULL,
 PRIMARY KEY (NUMERO_PEDIDO,ID_MENU)) ENGINE = INNODB;


ALTER TABLE REPARTIDOR ADD UNIQUE ALTER_KEY2 (DNI_REPARTIDOR);

ALTER TABLE PEDIDO ADD FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PRODUCTO ADD FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTE (ID_RESTAURANTE) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PEDIDO ADD FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTE (ID_RESTAURANTE) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE MENU ADD FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTE (ID_RESTAURANTE) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PEDIDO ADD FOREIGN KEY (ID_REPARTIDOR) REFERENCES REPARTIDOR (ID_REPARTIDOR) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE DETALLE_PEDIDO_PRODUCTO ADD FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PRODUCTOS_MENU ADD FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE DETALLE_PEDIDO_PRODUCTO ADD FOREIGN KEY (NUMERO_PEDIDO) REFERENCES PEDIDO (NUMERO_PEDIDO) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE DETALLE_PEDIDO_MENU ADD FOREIGN KEY (NUMERO_PEDIDO) REFERENCES PEDIDO (NUMERO_PEDIDO) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PRODUCTOS_MENU ADD FOREIGN KEY (ID_MENU) REFERENCES MENU (ID_MENU) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE DETALLE_PEDIDO_MENU ADD FOREIGN KEY (ID_MENU) REFERENCES MENU (ID_MENU) ON DELETE CASCADE ON UPDATE CASCADE;

